# Generated by Django 5.0.2 on 2024-02-11 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0002_alter_booking_no_of_guests"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="inventory",
            field=models.SmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "Inventory can't be negative"
                    ),
                    django.core.validators.MaxValueValidator(
                        99999, "Inventory can't exceed 99 999."
                    ),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booking",
            name="name",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, "Your name can't be an empty string."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="no_of_guests",
            field=models.SmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "You can't invite a negative number of guests."
                    ),
                    django.core.validators.MaxValueValidator(
                        999999, "Number of guests can't exceed 999 999."
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "Menu item's price can't be negative."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="title",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(
                        "Menu item's name can't be an empty string"
                    )
                ],
            ),
        ),
    ]
