# Generated by Django 5.0.2 on 2024-02-11 11:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0003_menu_inventory_alter_booking_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_date",
            field=models.DateTimeField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime.today, "You can't book a table in the past."
                    )
                ]
            ),
        ),
    ]
