# Generated by Django 5.0.2 on 2024-02-11 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0005_alter_booking_booking_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="title",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, "Menu item's name can't be an empty string"
                    )
                ],
            ),
        ),
    ]
